// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Courier_Management_System.Migrations.Employee
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Courier_Management_System.Models.Employee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emp_address")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_email")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_password")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_role")
                        .HasColumnType("TEXT");

                    b.HasKey("emp_id");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
