// <auto-generated />
using System;
using Courier_Management_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Courier_Management_System.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201118082534_statusmigration")]
    partial class statusmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Courier_Management_System.Models.City", b =>
                {
                    b.Property<string>("city_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("branch_address")
                        .HasColumnType("TEXT");

                    b.Property<long>("city_pincode")
                        .HasColumnType("INTEGER");

                    b.HasKey("city_name");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Courier_Management_System.Models.Consignment_Details", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Consignee_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<float>("amount")
                        .HasColumnType("REAL");

                    b.Property<long>("consignment_no")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("destination_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("package_content")
                        .HasColumnType("TEXT");

                    b.Property<string>("package_type")
                        .HasColumnType("TEXT");

                    b.Property<float>("pkg_weight_in_grams")
                        .HasColumnType("REAL");

                    b.Property<string>("user")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Consignment_Details");
                });

            modelBuilder.Entity("Courier_Management_System.Models.Consignment_Status", b =>
                {
                    b.Property<long>("pkg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("consignee_name")
                        .HasColumnType("TEXT");

                    b.Property<long>("consignment_no")
                        .HasColumnType("INTEGER");

                    b.Property<string>("current_city")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("user")
                        .HasColumnType("TEXT");

                    b.HasKey("pkg_id");

                    b.ToTable("Consignment_Status");
                });

            modelBuilder.Entity("Courier_Management_System.Models.Employee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emp_address")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_email")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_password")
                        .HasColumnType("TEXT");

                    b.Property<string>("emp_role")
                        .HasColumnType("TEXT");

                    b.HasKey("emp_id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Courier_Management_System.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
